config/routes.rb
Rails.application.routes.draw do
  root :to => 'static_pages#home'
  get 'sessions/new'
  get 'static_pages/home'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  resources :tasks
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to:user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true

  enum status: { not_started:0, in_progress:1, compleated:2 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many:tasks
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper

    def index
    end

    def autheniticate_user
      if current_user==nil
        flash[:notice]="ログインが必要です"
        redirect_to("/login")
      end
    end

    def forbid_login_user
      @user = User.find(params[:id])
        if not @user == current_user
          redirect_to current_user
        end
    end

    private
   # ログイン済みユーザーかどうか確認
    def logged_in_user
      unless logged_in?
        redirect_to login_url
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      render 'new'
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :current_user, only: [:destroy, :update]

    def new
        @task = Task.new
    end
    
    def index
        @tasks = current_user.tasks.all
    end

    def show
        @task = Task.find(params[:id])
    end

    def create
        @task = current_user.tasks.create(task_params)
        @task.save
        redirect_to current_user
    end

    def edit
        @task = Task.find(params[:id])
    end
    
    def update
        @task = Task.find(params[:id])
        @task.update(task_params)
        redirect_to current_user
    end

    def destroy
        @task = Task.find(params[:id])
        @task.destroy
        redirect_to current_user
    end

    private
        def task_params
          params.require(:task).permit(:title, :content, :status)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :autheniticate_user, only: [:index, :show]
  before_action :forbid_login_user, only: [:show]

  def index
    @user = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save
    log_in @user
    redirect_to @user
  end

  def show
    @user = User.find(params[:id])
    @tasks = @user.tasks.all

    if params[:status].present?
      @tasks = @tasks.where(status: params[:status])
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
   
    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        if session[:user_id]
          @current_user ||= User.find_by(id: session[:user_id])
        end
    end

    def logged_in?
        !current_user.nil?
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TsukasaRailsTodoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
      <div class="container-fluid">
        <a class="navbar-brand">TsukasaRailsTodoApp</a>
        <form class="d-flex">
          <%= link_to "Log in", '/login', method: :get, class: "btn btn-outline-primary"%>
        </form>
      </div>
    </nav>
  <%= yield %>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TsukasaRailsTodoApp
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    .header
      .nav
        = link_to "ログイン", '#'
  = yield

app/views/static_pages/home.html.erb
<div class="position-absolute top-50 start-50 translate-middle">
  <h1 class="fw-lighter text-secondary text-center lh-lg">TODO App</h1> 
  <h2 class="fw-lighter  text-secondary text-center lh-lg">自分のTODOを管理しましょう。</h2>
  <%= link_to '新規登録はこちらから', '/users/new', class:"btn btn-primary d-grid gap-2 col-6 mx-auto lh-lg mt-4"%>
</div>

app/views/static_pages/home.html.haml
:css
  .container {
    background-color: pink;
    font-size: x-large;
    height: 300px;
    text-align: center;
  }



.container
  %h1 TODO アプリ
  %h2 自分のTODOを管理しましょう。
  = button_to "新規登録はこちらから", {controller: 'static_pages', action: 'home'}, {method: :get}




 


    

app/views/tasks/edit.html.erb
<h1 class="fw-lighter text-center">To Do edit</h1>

<div class="col-md-6 col-md-offset-3 mx-auto mt-4">
  <%= form_with model:@task do |f| %>
    <%= f.label :title, class:"fw-lighter mb-2"%>
    <%= f.text_field :title, class:"form-control mb-3" %>
    <%= f.label :content, class:"fw-lighter mb-2"%>
    <%= f.text_area :content, class:"form-control mb-3" %>
    <%= f.label :status, class:"fw-lighter mb-2"%>
    <%= f.select :status, Task.statuses.keys.to_a, {}, class: "form-select form-select-sm mb-3"%>
    <%= f.submit "編集完了する", class:"btn btn-info mb-3" %>
  <% end %>
</div>
<div class="col-md-6 col-md-offset-3 mx-auto mt-4">
  <%= link_to "戻る", tasks_path, class:"btn btn-primary d-grid gap-2 col-6 mx-auto" %>
</div>

app/views/tasks/edit.html.haml
%h1 TODO編集
= form_for(@task) do |f|
  %div= f.label :title
  %div= f.text_field :title
  %div= f.submit
= link_to '戻る', tasks_path

app/views/tasks/index.html.erb
<h1 class="fw-lighter text-center">To Do list</h1>

<table class="mx-auto mt-4">
  <thead>
    <th class="fw-lighter text-center">title</th>
    <th class="fw-lighter text-center">content</th>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.content %></td>
        <td><%= link_to '編集する', edit_task_path(task), class:"btn btn-info" %></td>
        <td><%= button_to '削除する', task_path(task), method: :delete, class:"btn btn-success", data:{confirm: "削除しますか？"}%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="mx-auto mt-4" style="width: 200px;">
  <%= link_to 'To Doを追加しましょう', new_task_path, class:"btn btn-primary " %>
</div>

app/views/tasks/index.html.haml
%h1 TODO LIST
%table
  %thead
    %tr
      %th TODO NAME
  %tbody
    - @tasks.each do |task|
      %tr
        %td= task.title
        %td= link_to '編集', edit_task_path(task)
        %td= button_to '削除', task_path(task), method: :delete
= link_to '追加', new_task_path

app/views/tasks/new.html.erb
<h1 class="fw-lighter text-center">To Do create</h1>

<div class="col-md-6 col-md-offset-3 mx-auto mt-4">
  <%= form_with model:@task do |f| %>
    <%= f.label :title, class:"fw-lighter mb-2"%>
    <%= f.text_field :title, class:"form-control mb-3" %>
    <%= f.label :content, class:"fw-lighter mb-2"%>
    <%= f.text_area :content, class:"form-control mb-3" %>
    <%= f.label :status, class:"fw-lighter mb-2"%>
    <%= f.select :status, Task.statuses.keys.to_a, {}, class: "form-select form-select-sm mb-3"%>
    <%= f.submit "ToDoを作成", class:"btn btn-info mb-3" %>
  <% end %>
</div>
<div class="col-md-6 col-md-offset-3 mx-auto mt-4">
  <%= link_to "戻る", tasks_path, class:"btn btn-primary d-grid gap-2 col-6 mx-auto" %>
</div>

app/views/tasks/new.html.haml
%h1 新規TODO
= form_for(@task) do |f|
  %div= f.label :title
  %div= f.text_field :title
  %div= f.submit
= link_to '戻る', tasks_path

app/views/users/index.html.erb
<h1 class="fw-lighter text-center">All Users</h1>

<ul class="users">
  <% @user.each do |user| %>
    <li>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1 class="fw-lighter text-center">Sign up</h1>

<div class="col-md-6 col-md-offset-3 mx-auto">
    <%= form_with model: @user  do |f| %>
    
      <%= f.label :name, class: "col-sm-3 control-label" %>
      <%= f.text_field :name, class: "form-control mb-4", placeholder:"User name" %>
 
      <%= f.label :email, class: "col-sm-3 control-label" %>
      <%= f.email_field :email, class: "form-control mb-4", placeholder:"name@example.co.jp"%>
   
      <%= f.label :password, class: "col-sm-3 control-label" %>
      <%= f.password_field :password,  class: "form-control mb-4", placeholder:"password"%>

      <%= f.label :password_confirmation, "Confirmation", class: "col-sm-3 control-label"%>
      <%= f.password_field :password_confirmation, class: "form-control mb-4", placeholder:"password confirmation"%>

      <%= f.submit "新規登録", class: "btn btn-primary d-grid gap-2 col-6 mx-auto"%>
    <% end %>

    <%= link_to "トップページに戻る", '/static_pages/home', class: "btn btn-success d-grid gap-2 col-6 mx-auto mt-4"%>
</div>

app/views/users/new.html.haml
%h1 Users#new
%p Find me in app/views/users/new.html.erb

app/views/users/show.html.erb
<h1 class="fw-lighter text-center">To Do list</h1>

<div class="mx-auto mt-4 row" style="width: 200px;">
  <%= form_with url: @current_user, method: :get do %>
  <%= select_tag "status", options_for_select(Task.statuses_i18n.invert, selected: params[:status]), class: 'col-sm-3 form-control' %>
  <%= submit_tag "検索", class: "btn btn-primary btn-block mt-2" %>
  <% end %>
</div>

<table class="mx-auto mt-4">
  <thead>
    <th class="fw-lighter text-center">title</th>
    <th class="fw-lighter text-center">content</th>
    <th class="fw-lighter text-center">status</th>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.content %></td>
        <td><%= task.status_i18n %></td>
        <td><%= link_to '編集する', edit_task_path(task), class:"btn btn-info" %></td>
        <td><%= button_to '削除する', task_path(task), { method: :delete, form: { data: { turbo_confirm: "本当に削除しますか？" } }, class:"btn btn-primary" }  %></td>
      </tr>
    <% end %> 
  </tbody>
</table>

<div class="mx-auto mt-4" style="width: 200px;">
  <%= link_to 'To Doを追加しましょう', new_task_path, class:"btn btn-primary " %>
</div>